<a href="https://colab.research.google.com/github/Gabriela-Alcaide/CNN_basica/blob/main/Acoes_mercado_financeiro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports.

In [ ]:
# Imports.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras import layers, models

from google.colab import files
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler



# sns.set(style='whitegrid')

# Arquivos.

In [ ]:
uploaded = files.upload()

Saving teste_BBAS.csv to teste_BBAS (4).csv
Saving teste_CSNA.csv to teste_CSNA (3).csv
Saving teste_PETR.csv to teste_PETR (2).csv
Saving teste_VALE.csv to teste_VALE (2).csv
Saving treino_BBAS.csv to treino_BBAS (4).csv
Saving treino_CSNA.csv to treino_CSNA (3).csv
Saving treino_PETR.csv to treino_PETR (2).csv
Saving treino_VALE.csv to treino_VALE (2).csv


In [ ]:
# BBAS.
treino_BBAS = pd.read_csv('treino_BBAS.csv')
teste_BBAS = pd.read_csv('teste_BBAS.csv')

# CSNA.
treino_CSNA = pd.read_csv('treino_CSNA.csv')
teste_CSNA = pd.read_csv('teste_CSNA.csv')

# PETR.
treino_PETR = pd.read_csv('treino_PETR.csv')
teste_PETR = pd.read_csv('teste_PETR.csv')

# VALE.
treino_VALE = pd.read_csv('treino_VALE.csv')
teste_VALE = pd.read_csv('teste_VALE.csv')

In [ ]:
# Slit em X e Y.

# BBAS.
treino_BBAS_x = treino_BBAS.drop('Label', axis=1)
treino_BBAS_x = treino_BBAS_x.select_dtypes(include=[np.number])

treino_BBAS_y = treino_BBAS['Label']

teste_BBAS_x = teste_BBAS.drop('Label', axis=1)
teste_BBAS_x = teste_BBAS_x.select_dtypes(include=[np.number])

teste_BBAS_y = teste_BBAS['Label']

# CSNA.
treino_CSNA_x = treino_CSNA.drop('Label', axis=1)
treino_CSNA_x = treino_CSNA_x.select_dtypes(include=[np.number])

treino_CSNA_y = treino_CSNA['Label']

teste_CSNA_x = teste_CSNA.drop('Label', axis=1)
teste_CSNA_x = teste_CSNA_x.select_dtypes(include=[np.number])

teste_CSNA_y = teste_CSNA['Label']

# PETR.
treino_PETR_x = treino_PETR.drop('Label', axis=1)
treino_PETR_x = treino_PETR_x.select_dtypes(include=[np.number])

treino_PETR_y = treino_PETR['Label']

teste_PETR_x = teste_PETR.drop('Label', axis=1)
teste_PETR_x = teste_PETR_x.select_dtypes(include=[np.number])

teste_PETR_y = teste_PETR['Label']

# VALE.
treino_VALE_x = treino_VALE.drop('Label', axis=1)
treino_VALE_x = treino_VALE_x.select_dtypes(include=[np.number])

treino_VALE_y = treino_VALE['Label']

teste_VALE_x = teste_VALE.drop('Label', axis=1)
teste_VALE_x = teste_VALE_x.select_dtypes(include=[np.number])

teste_VALE_y = teste_VALE['Label']

In [ ]:
# Codificação dos rótulos.

# BBAS.
encoder = LabelEncoder()
treino_BBAS_y = encoder.fit_transform(treino_BBAS_y)
teste_BBAS_y = encoder.transform(teste_BBAS_y)

# CSNA.
encoder = LabelEncoder()
treino_CSNA_y = encoder.fit_transform(treino_CSNA_y)
teste_CSNA_y = encoder.transform(teste_CSNA_y)

# PETR.
encoder = LabelEncoder()
treino_PETR_y = encoder.fit_transform(treino_PETR_y)
teste_PETR_y = encoder.transform(teste_PETR_y)

# VALE.
encoder = LabelEncoder()
treino_VALE_y = encoder.fit_transform(treino_VALE_y)
teste_VALE_y = encoder.transform(teste_VALE_y)

# Escalonar

In [ ]:
# BBAS.
scaler = MinMaxScaler()
treino_BBAS_x = scaler.fit_transform(treino_BBAS_x)
teste_BBAS_x = scaler.transform(teste_BBAS_x)

# CSNA.
scaler = MinMaxScaler()
treino_CSNA_x = scaler.fit_transform(treino_CSNA_x)
teste_CSNA_x = scaler.transform(teste_CSNA_x)

# PETR.
scaler = MinMaxScaler()
treino_PETR_x = scaler.fit_transform(treino_PETR_x)
teste_PETR_x = scaler.transform(teste_PETR_x)

# VALE.
scaler = MinMaxScaler()
treino_VALE_x = scaler.fit_transform(treino_VALE_x)
teste_VALE_x = scaler.transform(teste_VALE_x)

# Ação BBAS.

In [ ]:
# Definindo e treinando um modelo CNN 1D
modelo_cnn_BBAS = models.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(treino_BBAS_x.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
#    layers.Dropout(0.3),
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
modelo_cnn_BBAS.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
treino_BBAS_x = treino_BBAS_x[..., np.newaxis]

In [ ]:
# Treinando o modelo
modelo_cnn_BBAS.fit(treino_BBAS_x[..., np.newaxis], treino_BBAS_y, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.5516 - loss: 0.6862 - val_accuracy: 0.5143 - val_loss: 0.7079
Epoch 2/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5720 - loss: 0.6780 - val_accuracy: 0.5143 - val_loss: 0.7873
Epoch 3/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5755 - loss: 0.6730 - val_accuracy: 0.5238 - val_loss: 0.7438
Epoch 4/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6325 - loss: 0.6485 - val_accuracy: 0.5744 - val_loss: 0.6758
Epoch 5/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6906 - loss: 0.6148 - val_accuracy: 0.8099 - val_loss: 0.4509
Epoch 6/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7224 - loss: 0.5677 - val_accuracy: 0.8036 - val_loss: 0.4288
Epoch 7/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7585 - loss: 0.5016 - val_accuracy: 0.8310 - val_loss: 0.3532
Epoch 8/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7961 - loss: 0.4521 - val_accuracy: 0.

In [ ]:
# Avaliação.
teste_BBAS_x = teste_BBAS_x[..., np.newaxis]

predicoes_BBAS = modelo_cnn_BBAS.predict(teste_BBAS_x[..., np.newaxis]).round()
print(f"Acurácia: {accuracy_score(teste_BBAS_y, predicoes_BBAS)}")
print("Matriz de Confusão:")
print(confusion_matrix(teste_BBAS_y, predicoes_BBAS))
print(classification_report(teste_BBAS_y, predicoes_BBAS))

38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Acurácia: 0.8430379746835444
Matriz de Confusão:
[[572 117]
 [ 69 427]]
              precision    recall  f1-score   support

           0       0.89      0.83      0.86       689
           1       0.78      0.86      0.82       496

    accuracy                           0.84      1185
   macro avg       0.84      0.85      0.84      1185
weighted avg       0.85      0.84      0.84      1185



# Ação CSNA.

In [ ]:
# Definindo e treinando um modelo CNN 1D.
modelo_cnn_CSNA = models.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(treino_CSNA_x.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
#    layers.Dropout(0.3),
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
modelo_cnn_CSNA.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
treino_CSNA_x = treino_CSNA_x[..., np.newaxis]

In [ ]:
# Treinando o modelo
modelo_cnn_CSNA.fit(treino_CSNA_x[..., np.newaxis], treino_CSNA_y, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5546 - loss: 0.6841 - val_accuracy: 0.5933 - val_loss: 0.6590
Epoch 2/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5763 - loss: 0.6692 - val_accuracy: 0.6333 - val_loss: 0.5758
Epoch 3/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7075 - loss: 0.5942 - val_accuracy: 0.7608 - val_loss: 0.4612
Epoch 4/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7884 - loss: 0.4934 - val_accuracy: 0.8714 - val_loss: 0.3690
Epoch 5/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8111 - loss: 0.4438 - val_accuracy: 0.8577 - val_loss: 0.3398
Epoch 6/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8243 - loss: 0.4125 - val_accuracy: 0.8556 - val_loss: 0.3273
Epoch 7/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8333 - loss: 0.3949 - val_accuracy: 0.8346 - val_loss: 0.3619
Epoch 8/20
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8477 - loss: 0.3746 - val_accuracy: 0.

In [ ]:
# Avaliação.
teste_CSNA_x = teste_CSNA_x[..., np.newaxis]

predicoes_CSNA = modelo_cnn_CSNA.predict(teste_CSNA_x[..., np.newaxis]).round()
print(f"Acurácia: {accuracy_score(teste_CSNA_y, predicoes_CSNA)}")
print("Matriz de Confusão:")
print(confusion_matrix(teste_CSNA_y, predicoes_CSNA))
print(classification_report(teste_CSNA_y, predicoes_CSNA))

38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Acurácia: 0.8591905564924115
Matriz de Confusão:
[[591  97]
 [ 70 428]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88       688
           1       0.82      0.86      0.84       498

    accuracy                           0.86      1186
   macro avg       0.85      0.86      0.86      1186
weighted avg       0.86      0.86      0.86      1186



# Ação PETR.

In [ ]:
# Definindo e treinando um modelo CNN 1D.
modelo_cnn_PETR = models.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(treino_PETR_x.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
#    layers.Dropout(0.3),
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
modelo_cnn_PETR.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
treino_PETR_x = treino_PETR_x[..., np.newaxis]

In [ ]:
# Treinando o modelo
modelo_cnn_PETR.fit(treino_PETR_x[..., np.newaxis], treino_PETR_y, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.5501 - loss: 0.6833 - val_accuracy: 0.5270 - val_loss: 0.6731
Epoch 2/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5922 - loss: 0.6648 - val_accuracy: 0.6632 - val_loss: 0.6149
Epoch 3/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6541 - loss: 0.6196 - val_accuracy: 0.7536 - val_loss: 0.5027
Epoch 4/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7642 - loss: 0.5212 - val_accuracy: 0.6102 - val_loss: 0.6427
Epoch 5/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7694 - loss: 0.5065 - val_accuracy: 0.8306 - val_loss: 0.3659
Epoch 6/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8222 - loss: 0.4256 - val_accuracy: 0.8815 - val_loss: 0.3062
Epoch 7/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8243 - loss: 0.4265 - val_accuracy: 0.8545 - val_loss: 0.3266
Epoch 8/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8354 - loss: 0.3970 - val_accuracy: 0

In [ ]:
# Avaliação.
teste_PETR_x = teste_PETR_x[..., np.newaxis]

predicoes_PETR = modelo_cnn_PETR.predict(teste_PETR_x[..., np.newaxis]).round()
print(f"Acurácia: {accuracy_score(teste_PETR_y, predicoes_PETR)}")
print("Matriz de Confusão:")
print(confusion_matrix(teste_PETR_y, predicoes_PETR))
print(classification_report(teste_PETR_y, predicoes_PETR))

38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
Acurácia: 0.8412302576891105
Matriz de Confusão:
[[494  87]
 [104 518]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       581
           1       0.86      0.83      0.84       622

    accuracy                           0.84      1203
   macro avg       0.84      0.84      0.84      1203
weighted avg       0.84      0.84      0.84      1203



# Ação VALE.

In [ ]:
# Definindo e treinando um modelo CNN 1D.
modelo_cnn_VALE = models.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(treino_VALE_x.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
#    layers.Dropout(0.3),
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
modelo_cnn_VALE.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
treino_VALE_x = treino_VALE_x[..., np.newaxis]

In [ ]:
# Treinando o modelo
modelo_cnn_VALE.fit(treino_VALE_x[..., np.newaxis], treino_VALE_y, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.5545 - loss: 0.6825 - val_accuracy: 0.5644 - val_loss: 0.6891
Epoch 2/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5825 - loss: 0.6699 - val_accuracy: 0.6320 - val_loss: 0.6331
Epoch 3/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6422 - loss: 0.6319 - val_accuracy: 0.6237 - val_loss: 0.5926
Epoch 4/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7045 - loss: 0.5698 - val_accuracy: 0.6559 - val_loss: 0.5963
Epoch 5/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7334 - loss: 0.5145 - val_accuracy: 0.7817 - val_loss: 0.4061
Epoch 6/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7557 - loss: 0.4839 - val_accuracy: 0.8358 - val_loss: 0.3716
Epoch 7/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7908 - loss: 0.4336 - val_accuracy: 0.8202 - val_loss: 0.3454
Epoch 8/20
121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8015 - loss: 0.4298 - val_accuracy: 0.

In [ ]:
# Avaliação.
teste_VALE_x = teste_VALE_x[..., np.newaxis]

predicoes_VALE = modelo_cnn_VALE.predict(teste_VALE_x[..., np.newaxis]).round()
print(f"Acurácia: {accuracy_score(teste_VALE_y, predicoes_VALE)}")
print("Matriz de Confusão:")
print(confusion_matrix(teste_VALE_y, predicoes_VALE))
print(classification_report(teste_VALE_y, predicoes_VALE))

38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Acurácia: 0.8536990856192851
Matriz de Confusão:
[[466 135]
 [ 41 561]]
              precision    recall  f1-score   support

           0       0.92      0.78      0.84       601
           1       0.81      0.93      0.86       602

    accuracy                           0.85      1203
   macro avg       0.86      0.85      0.85      1203
weighted avg       0.86      0.85      0.85      1203

